#name : try catch
# --
try {
    $0;
} catch(e) {
    console.error('error : ' + e);
}